name: GoTest

on:
  pull_request:
    branches: [ main, dev ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19
        id: go

      - name: Change to system directory
        run: cd system

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod tidy

      - name: Test
        run: go test -v ./...
